version: '3'

services:
  vue:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
#    command: npm run serve
    stdin_open: true
    tty: true
